import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding RPG items and bosses in backend database...");

  const items = [
    {
      name: "Rustblade Dagger",
      description: "A swift starter blade forged for quick strikes and agile habits.",
      category: "WEAPON",
      rarity: "Common",
      cost: 40,
      statBonusType: "agility",
      statBonusValue: 2,
      icon: "Sword",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Iron Greatsword",
      description: "Heavy steel blade that rewards rigorous strength training and discipline.",
      category: "WEAPON",
      rarity: "Uncommon",
      cost: 100,
      statBonusType: "strength",
      statBonusValue: 5,
      icon: "Swords",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Spellweaver Obsidian Staff",
      description: "Channels arcane knowledge directly into productive focus bursts.",
      category: "WEAPON",
      rarity: "Rare",
      cost: 180,
      statBonusType: "intellect",
      statBonusValue: 8,
      icon: "Wand2",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Paladin's Sunforged Warhammer",
      description: "Blessed hammer radiating glowing golden light upon quest completions.",
      category: "WEAPON",
      rarity: "Epic",
      cost: 350,
      statBonusType: "strength",
      statBonusValue: 12,
      icon: "Hammer",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Voidpiercer Bow",
      description: "Legendary weapon crafted in astral stillness. Strikes down high-priority tasks.",
      category: "WEAPON",
      rarity: "Legendary",
      cost: 600,
      statBonusType: "agility",
      statBonusValue: 18,
      icon: "Sparkles",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Leather Adventurer Tunic",
      description: "Lightweight leather armor providing comfort during long focus sessions.",
      category: "ARMOR",
      rarity: "Common",
      cost: 50,
      statBonusType: "vitality",
      statBonusValue: 3,
      icon: "Shield",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Chainmail Vanguard Cuirass",
      description: "Interlinked steel rings that shrug off fatigue and mental resistance.",
      category: "ARMOR",
      rarity: "Uncommon",
      cost: 140,
      statBonusType: "vitality",
      statBonusValue: 7,
      icon: "ShieldAlert",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Robes of the Arcane Scholar",
      description: "Silk woven with memory crystals that boost mental retention and stamina.",
      category: "ARMOR",
      rarity: "Rare",
      cost: 240,
      statBonusType: "intellect",
      statBonusValue: 10,
      icon: "Sparkle",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Aegis of the Colossus",
      description: "Impenetrable plate forged from volcanic adamant. Grants ironclad resilience.",
      category: "ARMOR",
      rarity: "Epic",
      cost: 450,
      statBonusType: "vitality",
      statBonusValue: 16,
      icon: "ShieldCheck",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Ring of Focus",
      description: "A silver ring set with a tranquil sapphire that enhances concentration.",
      category: "ACCESSORY",
      rarity: "Common",
      cost: 65,
      statBonusType: "intellect",
      statBonusValue: 3,
      icon: "CircleDot",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Amulet of Iron Will",
      description: "Pulsates with steady warmth whenever tasks become difficult.",
      category: "ACCESSORY",
      rarity: "Uncommon",
      cost: 120,
      statBonusType: "strength",
      statBonusValue: 6,
      icon: "Flame",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Crown of Charisma",
      description: "Golden circlet that shines when communicating, inspiring, and networking.",
      category: "ACCESSORY",
      rarity: "Rare",
      cost: 220,
      statBonusType: "charisma",
      statBonusValue: 10,
      icon: "Crown",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Potion of Vital Renewal",
      description: "Restores 50 Hit Points instantly. Essential after tough mental workouts.",
      category: "POTION",
      rarity: "Common",
      cost: 25,
      statBonusType: "currentHp",
      statBonusValue: 50,
      icon: "Heart",
      isConsumable: true,
      isEquippable: false,
    },
    {
      name: "Elixir of Arcane Clarity",
      description: "Restores 35 Mana Points to fuel daily quest bursts.",
      category: "POTION",
      rarity: "Common",
      cost: 25,
      statBonusType: "currentMana",
      statBonusValue: 35,
      icon: "Zap",
      isConsumable: true,
      isEquippable: false,
    },
    {
      name: "Scroll of XP Surge",
      description: "Ancient papyrus that instantly awards 150 Experience Points to your hero.",
      category: "POTION",
      rarity: "Rare",
      cost: 110,
      statBonusType: "currentXp",
      statBonusValue: 150,
      icon: "Scroll",
      isConsumable: true,
      isEquippable: false,
    },
    {
      name: "Cozy Tavern Hearth",
      description: "Warm amber illumination and rustic oak aesthetics for your dashboard.",
      category: "THEME",
      rarity: "Uncommon",
      cost: 100,
      statBonusType: "theme",
      statBonusValue: 1,
      icon: "Compass",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Cyberpunk Neon Grid",
      description: "High-tech synthwave aesthetic with pulsing electric cyan and magenta glows.",
      category: "THEME",
      rarity: "Rare",
      cost: 180,
      statBonusType: "theme",
      statBonusValue: 2,
      icon: "Zap",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Crimson Abyss Dungeon",
      description: "Dark, ominous castle aesthetic fit for a legendary dungeon conqueror.",
      category: "THEME",
      rarity: "Epic",
      cost: 260,
      statBonusType: "theme",
      statBonusValue: 3,
      icon: "Skull",
      isConsumable: false,
      isEquippable: true,
    },
    {
      name: "Badge: S-Rank Taskmaster",
      description: "Title badge displayed on your public character profile banner.",
      category: "BADGE",
      rarity: "Epic",
      cost: 200,
      statBonusType: "badge",
      statBonusValue: 1,
      icon: "Award",
      isConsumable: false,
      isEquippable: true,
    },
  ];

  for (const item of items) {
    const existing = await prisma.item.findFirst({ where: { name: item.name } });
    if (!existing) {
      await prisma.item.create({ data: item });
    }
  }

  const bosses = [
    {
      name: "The Procrastination Behemoth",
      title: "Sloth Lord of the Foggy Moors",
      description: "A towering sludge fiend that drains human willpower. Slay it by completing your daily quests!",
      maxHp: 300,
      currentHp: 300,
      level: 2,
      rewardXp: 300,
      rewardGold: 150,
      badgeReward: "Bane of Sloth",
      avatar: "Behemoth",
      isActive: true,
    },
    {
      name: "The Chimera of Distractions",
      title: "Devourer of Working Hours",
      description: "A three-headed beast of social media feeds and endless rabbit holes.",
      maxHp: 650,
      currentHp: 650,
      level: 5,
      rewardXp: 700,
      rewardGold: 350,
      badgeReward: "Laser Focused",
      avatar: "Chimera",
      isActive: false,
    },
    {
      name: "The Burnout Dragon",
      title: "Incinerator of Mortal Energy",
      description: "The supreme dread boss. Conquer it through disciplined balance and steady daily habits.",
      maxHp: 1500,
      currentHp: 1500,
      level: 10,
      rewardXp: 2000,
      rewardGold: 1000,
      badgeReward: "Dragon Sovereign",
      avatar: "Dragon",
      isActive: false,
    },
  ];

  for (const boss of bosses) {
    const existing = await prisma.boss.findFirst({ where: { name: boss.name } });
    if (!existing) {
      await prisma.boss.create({ data: boss });
    }
  }

  console.log("Backend database seeded successfully with catalog items and bosses!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
